import { addTrend } from "./trendService";
import type { FashionTrend } from "./trendService";

const sampleTrends: Omit<FashionTrend, "id">[] = [
  {
    name: "Quiet Luxury",
    category: "Quiet Luxury",
    subCategories: ["Outerwear", "Monochromatic", "Loafers"],
    season: "Spring",
    popularity: 0.9,
    description: "Understated elegance with high-quality materials and timeless designs.",
    keyItems: ["Cashmere sweaters", "Tailored trousers", "Minimal accessories"],
    createdAt: new Date(),
    updatedAt: new Date(),
    gender: "Unisex",
    priceRange: "Luxury",
    sustainability: true,
    culturalInfluence: "European minimalism",
    colorPalette: ["Beige", "Cream", "Navy", "Black"],
    fabricTypes: ["Cashmere", "Wool", "Silk", "Cotton"],
    imageUrl: "https://images.unsplash.com/photo-1483985988355-763728e1935b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80",
  },
  {
    name: "Gorpcore",
    category: "Gorpcore",
    subCategories: ["Outerwear", "Cargo", "Sneakers"],
    season: "Fall",
    popularity: 0.85,
    description: "Outdoor-inspired fashion meets urban style.",
    keyItems: ["Technical jackets", "Hiking boots", "Cargo pants"],
    createdAt: new Date(),
    updatedAt: new Date(),
    gender: "Unisex",
    priceRange: "Mid-Range",
    sustainability: true,
    culturalInfluence: "Outdoor recreation",
    colorPalette: ["Olive", "Black", "Orange", "Blue"],
    fabricTypes: ["Gore-Tex", "Nylon", "Fleece"],
    imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=720&q=80",
  },
  {
    name: "Old Money",
    category: "Old Money",
    subCategories: ["Outerwear", "Plaid", "Loafers"],
    season: "Fall",
    popularity: 0.88,
    description: "Classic, sophisticated style with a focus on quality and tradition.",
    keyItems: ["Tweed blazers", "Oxford shirts", "Pleated trousers"],
    createdAt: new Date(),
    updatedAt: new Date(),
    gender: "Unisex",
    priceRange: "Luxury",
    sustainability: true,
    culturalInfluence: "British aristocracy",
    colorPalette: ["Navy", "Burgundy", "Forest Green", "Brown"],
    fabricTypes: ["Tweed", "Wool", "Cotton", "Leather"],
    imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=720&q=80",
  },
  {
    name: "Grandpacore",
    category: "Grandpacore",
    subCategories: ["Vintage", "Argyle", "Cardigans"],
    season: "Winter",
    popularity: 0.82,
    description: "Nostalgic style inspired by classic grandfather fashion.",
    keyItems: ["Knit sweaters", "Pleated pants", "Leather shoes"],
    createdAt: new Date(),
    updatedAt: new Date(),
    gender: "Unisex",
    priceRange: "Mid-Range",
    sustainability: true,
    culturalInfluence: "Vintage Americana",
    colorPalette: ["Brown", "Beige", "Olive", "Navy"],
    fabricTypes: ["Wool", "Tweed", "Leather", "Cotton"],
    imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=720&q=80",
  },
  {
    name: "Dark Academia",
    category: "Dark Academia",
    subCategories: ["Outerwear", "Plaid", "Loafers"],
    season: "Fall",
    popularity: 0.8,
    description: "Intellectual aesthetic with vintage academic influences.",
    keyItems: ["Tweed blazers", "Oxford shirts", "Pleated skirts"],
    createdAt: new Date(),
    updatedAt: new Date(),
    gender: "Unisex",
    priceRange: "Mid-Range",
    sustainability: true,
    culturalInfluence: "Academic tradition",
    colorPalette: ["Navy", "Burgundy", "Forest Green", "Brown"],
    fabricTypes: ["Tweed", "Wool", "Cotton", "Leather"],
    imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=720&q=80",
  },
  {
    name: "Coquette",
    category: "Coquette",
    subCategories: ["Pastel", "Bold Prints", "Espadrilles"],
    season: "Summer",
    popularity: 0.75,
    description: "Feminine and romantic style with vintage touches.",
    keyItems: ["Lace dresses", "Pearl accessories", "Ribbon details"],
    createdAt: new Date(),
    updatedAt: new Date(),
    gender: "Women",
    priceRange: "Mid-Range",
    sustainability: false,
    culturalInfluence: "French fashion",
    colorPalette: ["Pink", "White", "Lavender", "Mint"],
    fabricTypes: ["Lace", "Silk", "Cotton", "Tulle"],
    imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=720&q=80",
  },
  {
    name: "Cottagecore",
    category: "Cottagecore",
    subCategories: ["Linen", "Pastel", "Espadrilles"],
    season: "Spring",
    popularity: 0.7,
    description: "Romantic, rural-inspired fashion with a focus on natural materials.",
    keyItems: ["Floral dresses", "Straw hats", "Lace details"],
    createdAt: new Date(),
    updatedAt: new Date(),
    gender: "Women",
    priceRange: "Mid-Range",
    sustainability: true,
    culturalInfluence: "Rural European lifestyle",
    colorPalette: ["Sage", "Cream", "Dusty Rose", "Mint"],
    fabricTypes: ["Linen", "Cotton", "Lace"],
    imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=720&q=80",
  },
  {
    name: "Mob Wife",
    category: "Mob Wife",
    subCategories: ["Outerwear", "Bold Prints", "Statement Belts"],
    season: "Winter",
    popularity: 0.78,
    description: "Bold, luxurious style with a touch of drama.",
    keyItems: ["Fur coats", "Animal prints", "Gold accessories"],
    createdAt: new Date(),
    updatedAt: new Date(),
    gender: "Women",
    priceRange: "Luxury",
    sustainability: false,
    culturalInfluence: "Italian-American culture",
    colorPalette: ["Black", "Gold", "Red", "Animal prints"],
    fabricTypes: ["Fur", "Silk", "Leather", "Velvet"],
    imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=720&q=80",
  },
  {
    name: "Balletcore",
    category: "Balletcore",
    subCategories: ["Pastel", "Layered Necklaces", "Espadrilles"],
    season: "Spring",
    popularity: 0.72,
    description: "Graceful, dance-inspired fashion with delicate details.",
    keyItems: ["Tulle skirts", "Wrap sweaters", "Ballet flats"],
    createdAt: new Date(),
    updatedAt: new Date(),
    gender: "Women",
    priceRange: "Mid-Range",
    sustainability: false,
    culturalInfluence: "Ballet and dance",
    colorPalette: ["Pink", "White", "Lavender", "Mint"],
    fabricTypes: ["Tulle", "Cotton", "Silk", "Lace"],
    imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=720&q=80",
  },
  {
    name: "Gothcore",
    category: "Gothcore",
    subCategories: ["Monochromatic", "Layered Necklaces", "Combat Boots"],
    season: "Fall",
    popularity: 0.68,
    description: "Dark, dramatic style with gothic influences.",
    keyItems: ["Black leather", "Victorian-inspired pieces", "Chunky boots"],
    createdAt: new Date(),
    updatedAt: new Date(),
    gender: "Unisex",
    priceRange: "Mid-Range",
    sustainability: false,
    culturalInfluence: "Gothic subculture",
    colorPalette: ["Black", "Deep Purple", "Blood Red", "Silver"],
    fabricTypes: ["Leather", "Velvet", "Lace", "Metal"],
    imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=720&q=80",
  },
  {
    name: "Boho Chic",
    category: "Boho Chic",
    subCategories: ["Layered Necklaces", "Bracelets", "Espadrilles"],
    season: "Summer",
    popularity: 0.65,
    description: "Free-spirited style with eclectic influences.",
    keyItems: ["Maxi dresses", "Fringe details", "Layered jewelry"],
    createdAt: new Date(),
    updatedAt: new Date(),
    gender: "Women",
    priceRange: "Mid-Range",
    sustainability: true,
    culturalInfluence: "Bohemian lifestyle",
    colorPalette: ["Earth tones", "Jewel tones", "Neutrals"],
    fabricTypes: ["Cotton", "Linen", "Crochet", "Leather"],
    imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=720&q=80",
  },
  {
    name: "Preppy",
    category: "Preppy",
    subCategories: ["Plaid", "Loafers", "Statement Belts"],
    season: "Spring",
    popularity: 0.75,
    description: "Classic, collegiate-inspired style.",
    keyItems: ["Polo shirts", "Khaki pants", "Sperry shoes"],
    createdAt: new Date(),
    updatedAt: new Date(),
    gender: "Unisex",
    priceRange: "Mid-Range",
    sustainability: false,
    culturalInfluence: "American collegiate",
    colorPalette: ["Navy", "Pink", "Green", "White"],
    fabricTypes: ["Cotton", "Wool", "Leather"],
    imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=720&q=80",
  }
];

export async function seedTrends() {
  try {
    console.log("Starting to seed trends...");
    for (const trend of sampleTrends) {
      const id = await addTrend(trend);
      console.log(`Added trend: ${trend.name} (ID: ${id})`);
    }
    console.log("Finished seeding trends!");
  } catch (error) {
    console.error("Error seeding trends:", error);
  }
} 