"""Check if outfits are being saved to Firestore"""
import os
import sys
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Add backend to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'backend'))

from src.config.firebase import db

# Check outfits collection
user_id = "dANqjiI0CKgaitxzYtw1bhtvQrG3"  # Your user ID

print("🔍 Checking outfits collection...")
outfits_ref = db.collection('outfits').where('user_id', '==', user_id).order_by('createdAt', direction='DESCENDING').limit(10)
outfits = list(outfits_ref.stream())

print(f"\n📊 Found {len(outfits)} outfits in last 10")

for outfit_doc in outfits:
    outfit = outfit_doc.to_dict()
    print(f"\n🎯 Outfit: {outfit.get('name', 'Unnamed')}")
    print(f"   - ID: {outfit_doc.id}")
    print(f"   - Occasion: {outfit.get('occasion', 'N/A')}")
    print(f"   - Style: {outfit.get('style', 'N/A')}")
    print(f"   - Items: {len(outfit.get('items', []))}")
    print(f"   - Created: {outfit.get('createdAt', 'N/A')}")
    print(f"   - Generated by: {outfit.get('generation_strategy', outfit.get('metadata', {}).get('generation_strategy', 'unknown'))}")

