# Nixpacks configuration for MCP service
[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "cd backend",
    "python3 -m pip install mcp httpx pydantic python-dotenv"
]

[start]
cmd = "cd backend && python3 mcp_server.py"

