# Nixpacks configuration for MCP service
[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
    "cd backend",
    "pip install mcp httpx pydantic python-dotenv"
]

[start]
cmd = "cd backend && python mcp_server.py"

