# Nixpacks configuration for MCP service
# Nixpacks auto-detects Python and uses pip if requirements.txt exists

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "cd backend && pip install -r requirements-mcp-minimal.txt"
]

[start]
cmd = "cd backend && python3 mcp_server.py"

