[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Build phase completed'"
]

[start]
cmd = "ls -la /app && find /app -name 'run.py' && python /app/run.py"
