[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

# Remove the start command to let railway.toml handle it
# This prevents conflicts with railway.toml configuration
