# Railway config for MCP service
# Uses main Dockerfile but overrides CMD to run MCP server

[build]
builder = "dockerfile"
sourceDir = "backend"

[deploy]
startCommand = "pip install mcp httpx && python3 mcp_server.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

