# Railway config for MCP service
# Uses lightweight Dockerfile.mcp and installs MCP at runtime

[build]
builder = "dockerfile"
sourceDir = "backend"
dockerfilePath = "Dockerfile.mcp"

[deploy]
startCommand = "pip install mcp httpx && python3 mcp_server.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

