[build]
builder = "dockerfile"
sourceDir = "backend"

[deploy]
startCommand = "gunicorn app:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[build.env]
NODE_ENV = "production"
NIXPACKS_PYTHON_VERSION = "3.11.12"
NIXPACKS_PIP_VERSION = "25.2"
