# Railway config for MCP service - uses dedicated MCP Dockerfile
# Root directory is "backend", so we're already in that folder
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.mcp"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

