# Railway config for MCP service - uses dedicated MCP Dockerfile
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.mcp"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

