# Railway config for MCP service - uses dedicated MCP Dockerfile
# Note: Root directory is set to "backend", so paths are relative to backend/
[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile.mcp"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

