# Railway config for MCP service
# Mirrors main app setup but uses Dockerfile.mcp instead of Dockerfile
# Root directory will be set to "backend" in Railway settings

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.mcp"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

