# Railway config for MCP service
# Mirrors main app setup: uses sourceDir instead of UI root directory

[build]
builder = "dockerfile"
sourceDir = "backend"
dockerfilePath = "Dockerfile.mcp"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

