# Railway configuration specifically for MCP service
# Use this for the closetgptrenewopenaisdk service

[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
phases.install.cmds = [
    "python3 -m pip install mcp httpx pydantic python-dotenv"
]

[deploy]
startCommand = "python3 mcp_server.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

