# Railway config for MCP service
# Uses same Dockerfile as main app, but overrides start command to run MCP server

[build]
builder = "dockerfile"
sourceDir = "backend"

[deploy]
startCommand = "pip install mcp httpx pydantic python-dotenv && python3 mcp_server.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

