[build]
builder = "NIXPACKS"

[deploy]
startCommand = "bash start_mcp.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
# Production environment for MCP server

