declare const beforeEach: jest.Lifecycle;
declare const afterEach: jest.Lifecycle;
declare const expect: jest.Expect;
declare const it: jest.It;
import React from 'react';
import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import BatchImageUpload from './BatchImageUpload';
import { persistBatchWardrobeItem } from '@/lib/persistBatchWardrobeItem';
let mockOnDrop: (files: File[]) => Promise<void>;
const mockToast = jest.fn();
const mockUser = { uid: 'test-owner', getIdToken: async () => 'upload-test-token' };
jest.mock('react-dropzone', () => ({ useDropzone: ({ onDrop }: { onDrop: typeof mockOnDrop }) => { mockOnDrop = onDrop; return { getRootProps: () => ({}), getInputProps: () => ({}), isDragActive: false }; } }));
jest.mock('@/components/ui/use-toast', () => ({ useToast: () => ({ toast: mockToast }) }));
jest.mock('@/lib/firebase-context', () => ({ useFirebase: () => ({ user: mockUser }) }));
jest.mock('@/lib/publicBackendUrl', () => ({ getPublicBackendUrl: () => 'https://api.example.test' }));
jest.mock('@/lib/persistBatchWardrobeItem', () => ({ persistBatchWardrobeItem: jest.fn() }));
jest.mock('../../lib/normalization', () => ({ normalizeItemMetadata: (item: unknown) => item }));
let originalFetch: typeof fetch;
let originalImage: typeof Image;
let mockFetch: jest.Mock;
let pendingAnalysis = false;
beforeEach(() => {
  originalFetch = global.fetch; originalImage = global.Image;
  jest.spyOn(console, 'log').mockImplementation(() => {});
  jest.spyOn(console, 'error').mockImplementation(() => {});
  jest.spyOn(console, 'warn').mockImplementation(() => {});
  URL.createObjectURL = jest.fn(() => 'blob:test'); URL.revokeObjectURL = jest.fn();
  global.Image = class { width = 100; height = 100; onload: null | (() => void) = null; set src(_value: string) { Promise.resolve().then(() => this.onload?.()); } } as unknown as typeof Image;
  jest.spyOn(HTMLCanvasElement.prototype, 'getContext').mockReturnValue({ drawImage: jest.fn() } as unknown as CanvasRenderingContext2D);
  jest.spyOn(HTMLCanvasElement.prototype, 'toBlob').mockImplementation(callback => callback(new Blob(['compressed'], { type: 'image/jpeg' })));
  pendingAnalysis = false;
  mockFetch = jest.fn(async url => ({ ok: true, json: async () => url === '/api/wardrobe' ? { success: true, items: [] } : url.endsWith('/api/image/upload') ? { image_url: 'https://images.example.test/shirt.jpg' } : url.endsWith('/generate-image-hash') ? { imageHash: 'testhash', metadata: { width: 100, height: 100, aspectRatio: 1 } } : { analysis: { name: 'White shirt', type: 'shirt', color: 'white' }, ...(pendingAnalysis ? { analysis_status: 'pending', client_item_id: 'pending-id' } : {}) } }));
  global.fetch = mockFetch;
  (persistBatchWardrobeItem as jest.Mock).mockReset();
  mockToast.mockClear();
});
afterEach(() => { global.fetch = originalFetch; global.Image = originalImage; jest.restoreAllMocks(); });
const selectAndStart = async () => {
  await act(async () => { await mockOnDrop([new File(['image'], 'shirt.jpg', { type: 'image/jpeg' })]); });
  fireEvent.click(screen.getByRole('button', { name: 'Upload & Analyze All (1 item)' }));
};
it.each(['normal', 'codex', 'quick'])('keeps a failed %s save out of completed garments and leaves its tile retryable', async mode => {
  pendingAnalysis = mode === 'codex';
  (persistBatchWardrobeItem as jest.Mock).mockRejectedValue(new Error('This item was not confirmed saved. Please retry.'));
  const onComplete = jest.fn();
  render(<BatchImageUpload userId="test-owner" quickMode={mode === 'quick'} onUploadComplete={onComplete} />);
  await selectAndStart();
  expect(await screen.findByRole('alert')).toHaveTextContent('not confirmed saved');
  await waitFor(() => expect(screen.getByRole('button', { name: 'Upload & Analyze All (1 item)' })).toBeEnabled());
  expect(onComplete).not.toHaveBeenCalled();
  expect(persistBatchWardrobeItem).toHaveBeenCalledTimes(1);
  expect(screen.getByText('shirt.jpg')).toBeVisible();
});
it.each(['normal', 'codex', 'quick'])('completes a %s upload only with the persisted record', async mode => {
  pendingAnalysis = mode === 'codex';
  const saved = { id: 'persisted-id', name: 'White shirt', userId: 'test-owner' };
  (persistBatchWardrobeItem as jest.Mock).mockResolvedValue(saved);
  const onComplete = jest.fn();
  render(<BatchImageUpload userId="test-owner" quickMode={mode === 'quick'} onUploadComplete={onComplete} />);
  await selectAndStart();
  await waitFor(() => expect(onComplete).toHaveBeenCalledWith([saved]));
  expect(persistBatchWardrobeItem).toHaveBeenCalledTimes(1);
});
