"""Railway-owned port of the accepted full questionnaire persistence contract.

Golden outputs in tests/fixtures/quiz-profile-parity.json were generated by the
original TypeScript mapping. In particular the submission receipt uses the same
JavaScript canonical JSON, so a retry across this migration remains a replay.
"""
import hashlib
import json
import math
from pathlib import Path
import re
import time

from firebase_admin import firestore


_DATA = json.loads(Path(__file__).with_name("quiz_profile_data.json").read_text())
REQUIRED_QUESTION_IDS = _DATA["required_question_ids"]
STYLE_PERSONAS = _DATA["personas"]


class QuizSubmissionError(Exception):
    def __init__(self, status_code, code, message):
        super().__init__(message)
        self.status_code, self.code, self.message = status_code, code, message


def js_truthy(value):
    # Empty arrays/objects are truthy in JavaScript. Do not replace them with
    # null in the receipt, or migrated lost-response retries would conflict.
    return value is not None and value is not False and value != "" and not (
        isinstance(value, (int, float)) and (value == 0 or (isinstance(value, float) and math.isnan(value)))
    )


def _js_trim(value):
    # JS String.trim includes BOM, but not Python's U+001C..U+001F separators.
    return value.strip("\u0009\u000a\u000b\u000c\u000d\u0020\u00a0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u2028\u2029\u202f\u205f\u3000\ufeff")


def _js_number(value):
    """JSON.stringify's binary64 decimal/exponent formatting (including -0)."""
    value = float(value)
    if not math.isfinite(value):
        return "null"
    if value == 0:
        return "0"
    negative = value < 0
    source = repr(abs(value)).lower()
    mantissa, _, exponent = source.partition("e")
    decimal = int(exponent or 0)
    if "." in mantissa:
        integer, fractional = mantissa.split(".")
        digits = integer + fractional
        decimal -= len(fractional)
    else:
        digits = mantissa
    digits = digits.lstrip("0")
    while digits.endswith("0"):
        digits = digits[:-1]
        decimal += 1
    position = len(digits) + decimal
    if 0 < position <= 21:
        result = digits[:position] + ("." + digits[position:] if position < len(digits) else "0" * (position - len(digits)))
    elif -6 < position <= 0:
        result = "0." + "0" * (-position) + digits
    else:
        power = position - 1
        result = digits[0] + ("." + digits[1:] if len(digits) > 1 else "") + "e" + ("+" if power >= 0 else "-") + str(abs(power))
    return ("-" if negative else "") + result


def _js_quote(value):
    encoded = json.dumps(value, ensure_ascii=False, separators=(",", ":"))
    # Modern JSON.stringify escapes lone UTF-16 surrogates, while preserving
    # ordinary Unicode and U+2028/U+2029. Python's encoder otherwise retains
    # lone surrogates that cannot be UTF-8 encoded for the SHA256 receipt.
    return re.sub(r"[\ud800-\udfff]", lambda match: "\\u%04x" % ord(match[0]), encoded)


def js_json(value, *, canonical=False):
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return _js_number(value)
    if isinstance(value, str):
        return _js_quote(value)
    if isinstance(value, list):
        return "[" + ",".join(js_json(item, canonical=canonical) for item in value) + "]"
    if isinstance(value, dict):
        keys = sorted(value, key=lambda key: key.encode("utf-16-be", "surrogatepass")) if canonical else list(value)
        # JS object enumeration always puts array-index keys before the other
        # keys, even after Object.fromEntries(Object.keys(...).sort()).
        indices = sorted((key for key in keys if re.fullmatch(r"0|[1-9][0-9]*", key) and int(key) < 4294967295), key=int)
        keys = indices + [key for key in keys if key not in indices]
        return "{" + ",".join(_js_quote(key) + ":" + js_json(value[key], canonical=canonical) for key in keys) + "}"
    raise ValueError("Quiz submission must be JSON data")


def submission_hash(submission, answers):
    value = {
        "answers": answers,
        "stylePreferences": submission.get("stylePreferences", []),
        "colorPreferences": submission.get("colorPreferences", []),
        "colorAnalysis": submission.get("colorAnalysis") if js_truthy(submission.get("colorAnalysis")) else None,
        "spendingRanges": submission.get("spending_ranges") if js_truthy(submission.get("spending_ranges")) else None,
    }
    return hashlib.sha256(js_json(value, canonical=True).encode("utf-8")).hexdigest()


def validate_submission(submission, identity):
    if not isinstance(submission, dict):
        raise QuizSubmissionError(422, "INVALID_SUBMISSION", "Invalid quiz submission.")
    if any(value is True or value == "true" or value == "1" or (type(value) in (int, float) and value == 1)
           for value in (submission.get(field) for field in ("guest", "guestMode", "isGuestFlow", "isGuest"))) or submission.get("mode") == "guest":
        raise QuizSubmissionError(403, "GUEST_WRITE_DENIED", "Guest answers must remain a draft until you continue the full questionnaire.")
    if any(field in submission and submission[field] != identity["uid"] for field in ("userId", "user_id", "firebase_uid", "uid")):
        raise QuizSubmissionError(403, "IDENTITY_MISMATCH", "The profile does not belong to the signed-in account.")
    raw = submission.get("answers")
    if not isinstance(raw, list) or not 1 <= len(raw) <= 100 or any(
        not isinstance(answer, dict) or not isinstance(answer.get("question_id"), str) or not answer["question_id"] or
        not isinstance(answer.get("selected_option"), str) or not _js_trim(answer["selected_option"]) for answer in raw
    ):
        raise QuizSubmissionError(422, "INVALID_ANSWERS", "Please complete the questionnaire before saving.")
    answers = {answer["question_id"]: answer["selected_option"] for answer in raw}
    if len(answers) != len(raw):
        raise QuizSubmissionError(422, "INVALID_ANSWERS", "Each question must have one answer.")
    if answers.get("gender") not in REQUIRED_QUESTION_IDS or any(not _js_trim(answers.get(question_id, "")) for question_id in REQUIRED_QUESTION_IDS.get(answers.get("gender"), [])):
        raise QuizSubmissionError(422, "FULL_QUIZ_REQUIRED", "Please finish the full questionnaire before saving your style profile.")
    for field in ("stylePreferences", "colorPreferences"):
        if field in submission and (not isinstance(submission[field], list) or any(not isinstance(value, str) for value in submission[field])):
            raise QuizSubmissionError(422, "INVALID_PREFERENCES", "Invalid style preferences.")
    return answers


def has_style_profile(profile):
    if not isinstance(profile, dict):
        return False
    text = lambda value: _js_trim(value) if isinstance(value, str) else ""
    persona = profile.get("stylePersona")
    preferences = profile.get("preferences")
    return js_truthy(profile.get("styleQuizCompletedAt")) or bool(
        text(persona.get("id")) or text(persona.get("name")) if isinstance(persona, dict) else text(persona)
    ) or any(isinstance(values, list) and any(text(entry) for entry in values) for values in (
        profile.get("stylePreferences"), profile.get("style_preferences"),
        preferences.get("style") if isinstance(preferences, dict) else None,
    ))


def _personality(styles, answers):
    scores = dict.fromkeys(("classic", "modern", "creative", "minimal", "bold"), 0.5)
    for style in styles:
        if style in ("Classic Elegant", "Old Money"):
            scores["classic"] += 0.3
            scores["minimal"] += 0.1
        elif style in ("Street Style", "Urban Street"):
            scores["bold"] += 0.3
            scores["creative"] += 0.2
        elif style in ("Minimalist", "Clean Minimal"):
            scores["minimal"] += 0.3
            scores["classic"] += 0.1
        elif style in ("Cottagecore", "Natural Boho"):
            scores["creative"] += 0.2
            scores["modern"] += 0.1
    if answers.get("daily_activities") == "Office work and meetings":
        scores["classic"] += 0.2
        scores["minimal"] += 0.1
    elif answers.get("daily_activities") == "Creative work and casual meetings":
        scores["creative"] += 0.2
        scores["modern"] += 0.1
    if answers.get("style_elements") == "Clean lines and minimal details":
        scores["minimal"] += 0.2
        scores["classic"] += 0.1
    elif answers.get("style_elements") == "Bold and statement pieces":
        scores["bold"] += 0.2
        scores["creative"] += 0.1
    return {key: max(0, min(1, value)) for key, value in scores.items()}


def _persona(styles, answers):
    scores = dict.fromkeys(STYLE_PERSONAS, 0)
    def add(changes):
        for key, amount in changes.items():
            scores[key] += amount
    for aliases, changes in (
        (("Minimalist", "Clean Minimal"), {"architect": 3, "modernist": 2}),
        (("Street Style", "Urban Street"), {"rebel": 3, "strategist": 1}),
        (("Classic Elegant",), {"classic": 3, "connoisseur": 2}),
        (("Old Money",), {"classic": 2, "connoisseur": 3}),
        (("Cottagecore", "Natural Boho"), {"wanderer": 3, "rebel": 1}),
    ):
        if any(style in styles for style in aliases):
            add(changes)
    add({
        "Office work and meetings": {"connoisseur": 2, "architect": 1, "classic": 1},
        "Creative work and casual meetings": {"modernist": 2, "rebel": 1, "innovator": 1},
        "Active lifestyle and sports": {"rebel": 2, "strategist": 1},
        "Mix of everything": {"modernist": 3, "strategist": 2},
    }.get(answers.get("daily_activities"), {}))
    add({
        "Clean lines and minimal details": {"architect": 3, "modernist": 2},
        "Rich textures and patterns": {"connoisseur": 3, "classic": 1},
        "Classic and timeless pieces": {"classic": 3, "connoisseur": 2, "architect": 1},
        "Bold and statement pieces": {"rebel": 3, "innovator": 1},
    }.get(answers.get("style_elements"), {}))
    # max preserves insertion order on ties, as the accepted stable JS sort did.
    return STYLE_PERSONAS[max(scores, key=scores.get)]


def map_quiz_answers_to_profile(answers, color_analysis, styles, colors, name="Quiz User", email="quiz@example.com", uid="quiz-user", spending_ranges=None, *, now=None):
    personality = _personality(styles, answers)
    persona = _persona(styles, answers)
    if not colors:
        palette = color_analysis.get("palette", {}) if isinstance(color_analysis, dict) else {}
        values = []
        for key in ("primary", "secondary", "accents"):
            raw = palette.get(key) if isinstance(palette, dict) else None
            if js_truthy(raw):
                # A malformed supplied palette fails before any profile write,
                # just as the prior spreading/filtering implementation did.
                values.extend(raw)
        colors = list(dict.fromkeys([value for value in values if js_truthy(value)][:8]))
    resolved_styles = styles or list(personality)
    body_type = answers.get("body_type_female") or answers.get("body_type_male") or answers.get("body_type_nonbinary") or ""
    skin_tone = answers.get("skin_tone", "")
    skin_tone = skin_tone if re.fullmatch(r"skin_tone_(?:100|[1-9]?\d)", skin_tone, flags=re.ASCII) else None
    now = math.floor(time.time()) if now is None else now
    update = {
        "name": name, "email": email, "userId": uid, "user_id": uid,
        "gender": answers.get("gender"), "bodyType": body_type, "skinTone": skin_tone,
        "measurements": {
            "height": answers.get("height") or "", "weight": answers.get("weight") or "", "bodyType": body_type,
            "skinTone": skin_tone, "topSize": answers.get("top_size") or "", "bottomSize": answers.get("bottom_size") or "",
            "shoeSize": answers.get("shoe_size_male") or answers.get("shoe_size_female") or answers.get("shoe_size") or "", "braSize": answers.get("cup_size") or "",
        },
        "heightFeetInches": answers.get("height") or "", "height": answers.get("height") or "", "weight": answers.get("weight") or "",
        "stylePreferences": resolved_styles,
        "preferences": {"style": resolved_styles, "colors": colors, "occasions": [answers.get("daily_activities") or ""]},
        "stylePersonality": personality,
        "colorPalette": {"primary": colors[:3], "secondary": colors[3:6], "accent": colors[6:9], "neutral": ["black", "white", "gray", "beige"], "avoid": []},
        "stylePersona": {key: value for key, value in persona.items() if key != "cta"},
        "updatedAt": now, "updated_at": now,
    }
    if js_truthy(spending_ranges):
        update["spending_ranges"] = spending_ranges
    for field, ids in {
        "height": ("height",), "weight": ("weight",), "bodyType": ("body_type_female", "body_type_male", "body_type_nonbinary"),
        "skinTone": ("skin_tone",), "topSize": ("top_size",), "bottomSize": ("bottom_size",),
        "shoeSize": ("shoe_size_male", "shoe_size_female", "shoe_size"), "braSize": ("cup_size",),
    }.items():
        if not any(question_id in answers for question_id in ids):
            update["measurements"].pop(field, None)
            update.pop(field, None)
            if field == "height":
                update.pop("heightFeetInches", None)
    if not update["measurements"]:
        update.pop("measurements")
    if not answers.get("gender"):
        update.pop("gender")
    if not answers.get("daily_activities"):
        update["preferences"].pop("occasions")
    if not colors:
        update["preferences"].pop("colors")
        update.pop("colorPalette")
    return update


def save_quiz_profile(db, identity, submission, *, now=None):
    answers = validate_submission(submission, identity)
    digest = submission_hash(submission, answers)
    reference = db.collection("users").document(identity["uid"])
    expected_epoch = None

    @firestore.transactional
    def save(transaction):
        nonlocal expected_epoch
        snapshot = reference.get(transaction=transaction)
        existing = snapshot.to_dict() or {} if snapshot.exists else {}
        from .app_data_privacy import app_data_write_allowed, data_epoch
        if not app_data_write_allowed(existing, expected_epoch):
            raise QuizSubmissionError(409, 'APP_DATA_CLEARING', 'Your app data is being cleared. Reload before saving.')
        if expected_epoch is None:
            expected_epoch = data_epoch(existing)
        if existing.get("styleQuizSubmissionHash") == digest and has_style_profile(existing):
            return existing
        if has_style_profile(existing) and submission.get("retake") is not True:
            raise QuizSubmissionError(409, "RETAKE_REQUIRED", "You already have a style profile. Choose Retake to replace it.")
        instant = math.floor(time.time()) if now is None else now
        email = identity.get("email") or existing.get("email") or ""
        name = identity.get("name") or existing.get("name") or (identity.get("email") or "").split("@")[0] or ""
        update = map_quiz_answers_to_profile(answers, submission.get("colorAnalysis"), submission.get("stylePreferences", []), submission.get("colorPreferences", []), name, email, identity["uid"], submission.get("spending_ranges"), now=instant)
        if "measurements" in update:
            update["measurements"] = {**(existing.get("measurements") or {}), **update["measurements"]}
        update["preferences"] = {**(existing.get("preferences") or {}), **update["preferences"]}
        created_at = existing.get("created_at")
        if created_at is None:
            created_at = existing.get("createdAt")
        update["created_at"] = instant if created_at is None else created_at
        update["styleQuizCompletedAt"] = instant
        update["styleQuizSubmissionHash"] = digest
        if js_truthy(submission.get("spending_ranges")) and (
            "spending_ranges" not in existing or js_json(existing["spending_ranges"]) != js_json(submission["spending_ranges"])
        ):
            update["tveRecalcStatus"] = "queued"
            update["tveRecalcRequestedAt"] = instant
        transaction.set(reference, update, merge=True)
        return update

    saved = save(db.transaction())
    return {
        "success": True, "persisted": True, "message": "Style profile saved successfully",
        "hybridStyleName": saved["stylePersona"]["name"],
        "quizResults": {"aesthetic_scores": saved.get("stylePersonality"), "color_season": answers.get("skin_tone") or None, "body_type": saved.get("bodyType") or None, "style_preferences": saved.get("stylePreferences")},
        "colorAnalysis": submission.get("colorAnalysis") if js_truthy(submission.get("colorAnalysis")) else None,
    }
