export const ALLOWED_STYLE_TYPES = [
  "Casual",
  "Formal",
  "Athletic / Gym",
  "Trendy",
  "Vintage",
  "Statement",
  "Smart Casual",
  "Business",
  "Luxury",
  "Streetwear",
  "Minimalist",
  "Bohemian",
  "Classic",
  "Elegant",
  "Athletic",
  "Preppy",
  "Gothic",
  "Punk",
  "Hipster",
  "Retro"
] as const;

export type StyleType = typeof ALLOWED_STYLE_TYPES[number];

export const ALLOWED_STYLE_SUBTYPES = {
  // --- CASUAL ---
  EVERYDAY: "Everyday",
  RELAXED: "Relaxed",
  COMFY: "Comfy",
  LOUNGEWEAR: "Loungewear",
  WEEKEND: "Weekend",
  DENIM_CASUAL: "Denim Casual",
  SUMMER_CASUAL: "Summer Casual",

  // --- FORMAL ---
  BLACK_TIE: "Black Tie",
  COCKTAIL: "Cocktail",
  EVENING_GOWN: "Evening Gown",
  TUXEDO: "Tuxedo",
  BRIDAL: "Bridal",
  GALA: "Gala",

  // --- ATHLETIC / GYM ---
  ACTIVEWEAR: "Activewear",
  GYM_WEAR: "Gym Wear",
  RUNNING: "Running",
  CYCLING: "Cycling",
  SWIMWEAR: "Swimwear",
  TENNISCORE: "Tenniscore",
  ATHLEISURE: "Athleisure",

  // --- TRENDY ---
  Y2K: "Y2K",
  FUTURISTIC: "Futuristic",
  COTTAGECORE: "Cottagecore",
  COASTAL_GRANDMA: "Coastal Grandma",
  GENDER_FLUID: "Gender Fluid",
  ECLECTIC: "Eclectic",
  CLEAN_GIRL: "Clean Girl",
  DARK_ACADEMIA: "Dark Academia",
  LIGHT_ACADEMIA: "Light Academia",

  // --- VINTAGE / RETRO ---
  SEVENTIES: "70s",
  EIGHTIES: "80s",
  NINETIES: "90s",
  MOD: "Mod",
  PINUP: "Pinup",
  OLD_MONEY: "Old Money",
  VINTAGE_CHANEL: "Vintage Chanel",

  // --- STATEMENT / ARTISTIC ---
  COLORBLOCK: "Colorblock",
  MAXIMALIST: "Maximalist",
  PRINT_ON_PRINT: "Print on Print",
  ART_POP: "Art Pop",
  BOLD_GRAPHICS: "Bold Graphics",
  AVANT_GARDE: "Avant-Garde",

  // --- SMART CASUAL / BUSINESS ---
  BUSINESS_CASUAL: "Business Casual",
  OFFICE_CHIC: "Office Chic",
  MONOCHROME_MINIMAL: "Monochrome Minimal",
  CLEAN_LINES: "Clean Lines",
  URBAN_PROFESSIONAL: "Urban Professional",

  // --- LUXURY / ELEGANT ---
  DESIGNER: "Designer",
  HIGH_FASHION: "High Fashion",
  SOPHISTICATED: "Sophisticated",
  FRENCH_GIRL: "French Girl",
  RED_CARPET: "Red Carpet",

  // --- STREETWEAR ---
  SKATE: "Skate",
  URBAN: "Urban",
  TECHWEAR: "Techwear",
  HYPEBEAST: "Hypebeast",
  GRUNGE: "Grunge",
  WORKWEAR: "Workwear",
  MILITARY: "Military Inspired",

  // --- BOHEMIAN ---
  FESTIVAL: "Festival",
  FOLK: "Folk",
  LAYERED: "Layered",
  ETHNIC_INFLUENCE: "Ethnic Influence",
  EARTH_TONES: "Earth Tones",

  // --- SUBCULTURE / NICHE ---
  PREPPY: "Preppy",
  GOTHIC: "Gothic",
  PUNK: "Punk",
  HIPSTER: "Hipster",
  EMO: "Emo",
  SCENE: "Scene",
  ALT: "Alt",

  // --- CLASSIC / MINIMALIST ---
  CLASSIC_CHIC: "Classic Chic",
  TIMELESS: "Timeless",
  JAPANESE_MINIMALISM: "Japanese Minimalism",
  SCANDI: "Scandinavian Minimalism",
  MONOCHROME: "Monochrome",
  MODERN_BASIC: "Modern Basic"
} as const;

export type StyleSubtype = typeof ALLOWED_STYLE_SUBTYPES[keyof typeof ALLOWED_STYLE_SUBTYPES];

export const STYLE_TYPE_MAPPING: Record<string, StyleType> = {
  "Business Casual": "Smart Casual",
  "Business-Casual": "Smart Casual",
  "Smart-Casual": "Smart Casual",
  "Athletic": "Athletic / Gym",
  "Basic": "Casual",
  "Luxury": "Formal",
  "Luxe": "Formal",
  "Edgy": "Statement",
  "Urban": "Trendy",
  "Streetwear": "Trendy",
  "Western": "Casual",
  "Retro": "Vintage",
  "Utility": "Casual"
};

export const STYLE_SUBTYPE_MAPPING: Record<string, StyleSubtype> = {
  // Add any mappings for style subtypes here
  "Active": "Activewear",
  "Gym": "Gym Wear",
  "Running": "Running",
  "Bike": "Cycling",
  "Swim": "Swimwear",
  "Tennis": "Tenniscore",
  "Athleisure": "Athleisure",
  "Y2K": "Y2K",
  "Futuristic": "Futuristic",
  "Cottage": "Cottagecore",
  "Coastal": "Coastal Grandma",
  "Gender Fluid": "Gender Fluid",
  "Eclectic": "Eclectic",
  "Clean": "Clean Girl",
  "Dark Academia": "Dark Academia",
  "Light Academia": "Light Academia",
  "70s": "70s",
  "80s": "80s",
  "90s": "90s",
  "Mod": "Mod",
  "Pinup": "Pinup",
  "Old Money": "Old Money",
  "Vintage Chanel": "Vintage Chanel",
  "Colorblock": "Colorblock",
  "Maximalist": "Maximalist",
  "Print on Print": "Print on Print",
  "Art Pop": "Art Pop",
  "Bold Graphics": "Bold Graphics",
  "Avant-Garde": "Avant-Garde",
  "Business Casual": "Business Casual",
  "Office Chic": "Office Chic",
  "Monochrome Minimal": "Monochrome Minimal",
  "Clean Lines": "Clean Lines",
  "Urban Professional": "Urban Professional",
  "Designer": "Designer",
  "High Fashion": "High Fashion",
  "Sophisticated": "Sophisticated",
  "French Girl": "French Girl",
  "Red Carpet": "Red Carpet",
  "Skate": "Skate",
  "Urban": "Urban",
  "Techwear": "Techwear",
  "Hypebeast": "Hypebeast",
  "Grunge": "Grunge",
  "Workwear": "Workwear",
  "Military": "Military Inspired",
  "Festival": "Festival",
  "Folk": "Folk",
  "Layered": "Layered",
  "Ethnic": "Ethnic Influence",
  "Earth Tones": "Earth Tones",
  "Preppy": "Preppy",
  "Gothic": "Gothic",
  "Punk": "Punk",
  "Hipster": "Hipster",
  "Emo": "Emo",
  "Scene": "Scene",
  "Alt": "Alt",
  "Classic Chic": "Classic Chic",
  "Timeless": "Timeless",
  "Japanese Minimalism": "Japanese Minimalism",
  "Scandinavian": "Scandinavian Minimalism",
  "Monochrome": "Monochrome",
  "Modern Basic": "Modern Basic"
};

export const CLOTHING_TYPES = {
  SHIRT: "shirt",
  PANTS: "pants",
  SKIRT: "skirt",
  DRESS: "dress",
  JACKET: "jacket",
  SWEATER: "sweater",
  SHOES: "shoes",
  ACCESSORY: "accessory",
  OTHER: "other"
} as const;

export type ClothingType = typeof CLOTHING_TYPES[keyof typeof CLOTHING_TYPES];

export const TYPE_MAPPING: Record<string, ClothingType> = {
  // Shirts
  "Tee": CLOTHING_TYPES.SHIRT,
  "T-Shirt": CLOTHING_TYPES.SHIRT,
  "Blouse": CLOTHING_TYPES.SHIRT,
  "Button-Up": CLOTHING_TYPES.SHIRT,
  "Polo": CLOTHING_TYPES.SHIRT,
  "Tank Top": CLOTHING_TYPES.SHIRT,
  "Crop Top": CLOTHING_TYPES.SHIRT,
  
  // Pants
  "Jeans": CLOTHING_TYPES.PANTS,
  "Joggers": CLOTHING_TYPES.PANTS,
  "Sweatpants": CLOTHING_TYPES.PANTS,
  "Chinos": CLOTHING_TYPES.PANTS,
  "Slacks": CLOTHING_TYPES.PANTS,
  "Shorts": CLOTHING_TYPES.PANTS,
  
  // Skirts
  "Mini Skirt": CLOTHING_TYPES.SKIRT,
  "Midi Skirt": CLOTHING_TYPES.SKIRT,
  "Maxi Skirt": CLOTHING_TYPES.SKIRT,
  "Pencil Skirt": CLOTHING_TYPES.SKIRT,
  
  // Dresses
  "Sundress": CLOTHING_TYPES.DRESS,
  "Cocktail Dress": CLOTHING_TYPES.DRESS,
  "Maxi Dress": CLOTHING_TYPES.DRESS,
  "Mini Dress": CLOTHING_TYPES.DRESS,
  
  // Jackets
  "Blazer": CLOTHING_TYPES.JACKET,
  "Bomber": CLOTHING_TYPES.JACKET,
  "Denim Jacket": CLOTHING_TYPES.JACKET,
  "Leather Jacket": CLOTHING_TYPES.JACKET,
  "Windbreaker": CLOTHING_TYPES.JACKET,
  
  // Sweaters
  "Cardigan": CLOTHING_TYPES.SWEATER,
  "Hoodie": CLOTHING_TYPES.SWEATER,
  "Pullover": CLOTHING_TYPES.SWEATER,
  "Turtleneck": CLOTHING_TYPES.SWEATER,
  
  // Shoes
  "Sneakers": CLOTHING_TYPES.SHOES,
  "Boots": CLOTHING_TYPES.SHOES,
  "Sandals": CLOTHING_TYPES.SHOES,
  "Heels": CLOTHING_TYPES.SHOES,
  "Flats": CLOTHING_TYPES.SHOES,
  "Loafers": CLOTHING_TYPES.SHOES,
  
  // Accessories
  "Hat": CLOTHING_TYPES.ACCESSORY,
  "Scarf": CLOTHING_TYPES.ACCESSORY,
  "Belt": CLOTHING_TYPES.ACCESSORY,
  "Jewelry": CLOTHING_TYPES.ACCESSORY,
  "Bag": CLOTHING_TYPES.ACCESSORY,
  "Watch": CLOTHING_TYPES.ACCESSORY
};

export const SEASONS = {
  SPRING: "spring",
  SUMMER: "summer",
  FALL: "fall",
  WINTER: "winter"
} as const;

export type Season = typeof SEASONS[keyof typeof SEASONS];

export const ADJACENT_SEASONS: Record<Season, Season[]> = {
  [SEASONS.SPRING]: [SEASONS.SUMMER, SEASONS.FALL],
  [SEASONS.SUMMER]: [SEASONS.SPRING, SEASONS.FALL],
  [SEASONS.FALL]: [SEASONS.SUMMER, SEASONS.WINTER],
  [SEASONS.WINTER]: [SEASONS.FALL, SEASONS.SPRING]
};

// Add the missing ALLOWED_STYLE_TAGS for StyleTagSelector
export const ALLOWED_STYLE_TAGS = [
  "Classic",
  "Casual",
  "Formal",
  "Business Casual",
  "Preppy",
  "Minimalist",
  "Streetwear",
  "Athleisure",
  "Vintage",
  "Trendy",
  "Bohemian",
  "Gothic",
  "Punk",
  "Hipster",
  "Retro",
  "Y2K",
  "Dark Academia",
  "Light Academia",
  "Cottagecore",
  "Coastal Chic",
  "Old Money",
  "Techwear",
  "Androgynous",
  "Romantic",
  "Artsy",
  "Avant-Garde",
  "Edgy",
  "Grunge",
  "Elegant",
  "Sophisticated",
  "Athletic / Gym",
  "Comfortable",
  "Professional",
  "Smart Casual",
  "Urban",
  "Modern",
  "Timeless",
  "Bold",
  "Subtle",
  "Colorful",
  "Neutral",
  "Monochrome",
  "Layered",
  "Simple",
  "Complex",
  "Structured",
  "Relaxed",
  "Fitted",
  "Oversized",
  "Tailored",
  "Loose",
  "Tight",
  "Flowy",
  "Stiff",
  "Soft",
  "Hard",
  "Smooth",
  "Textured",
  "Shiny",
  "Matte",
  "Transparent",
  "Opaque",
  "Light",
  "Dark",
  "Bright",
  "Muted",
  "Warm",
  "Cool",
  "Neutral",
  "Pastel",
  "Vibrant",
  "Earth Tones",
  "Jewel Tones",
  "Metallic",
  "Iridescent",
  "Holographic",
  "Glitter",
  "Sequins",
  "Embroidery",
  "Applique",
  "Patchwork",
  "Tie-dye",
  "Batik",
  "Bleached",
  "Distressed",
  "Faded",
  "Vintage Wash",
  "Raw Denim",
  "Stretch",
  "Rigid",
  "Breathable",
  "Waterproof",
  "Insulated",
  "Lightweight",
  "Heavy",
  "Thin",
  "Thick",
  "Sheer",
  "Solid",
  "Striped",
  "Plaid",
  "Floral",
  "Geometric",
  "Abstract",
  "Animal Print",
  "Polka Dot",
  "Checkered",
  "Houndstooth",
  "Herringbone",
  "Tweed",
  "Cable Knit",
  "Ribbed",
  "Corduroy",
  "Velvet",
  "Satin",
  "Silk",
  "Cotton",
  "Linen",
  "Wool",
  "Cashmere",
  "Denim",
  "Leather",
  "Suede",
  "Faux Fur",
  "Mesh",
  "Lace",
  "Crochet",
  "Knit",
  "Woven",
  "Jersey",
  "Fleece",
  "Terry Cloth",
  "Canvas",
  "Twill",
  "Poplin",
  "Chiffon",
  "Organza",
  "Taffeta",
  "Brocade",
  "Damask",
  "Jacquard",
  "Boucle",
  "Chenille",
  "Tweed",
  "Herringbone",
  "Houndstooth",
  "Gingham",
  "Madras",
  "Seersucker",
  "Oxford",
  "Chambray",
  "Voile",
  "Batiste",
  "Muslin",
  "Calico",
  "Percale",
  "Sateen",
  "Flannel",
  "Felt",
  "Tweed",
  "Boucle",
  "Chenille",
  "Velour",
  "Velveteen",
  "Corduroy",
  "Cord",
  "Rib",
  "Cable",
  "Aran",
  "Fair Isle",
  "Argyle",
  "Diamond",
  "Chevron",
  "Zigzag",
  "Wave",
  "Spiral",
  "Circle",
  "Square",
  "Triangle",
  "Hexagon",
  "Octagon",
  "Star",
  "Heart",
  "Diamond",
  "Club",
  "Spade",
  "Cross",
  "Crown",
  "Anchor",
  "Anchor",
  "Compass",
  "Map",
  "Globe",
  "Flag",
  "Banner",
  "Ribbon",
  "Bow",
  "Tie",
  "Knot",
  "Chain",
  "Link",
  "Ring",
  "Circle",
  "Dot",
  "Spot",
  "Speckle",
  "Fleck",
  "Stain",
  "Splash",
  "Drip",
  "Drop",
  "Splash",
  "Spray",
  "Mist",
  "Fog",
  "Smoke",
  "Cloud",
  "Rain",
  "Snow",
  "Ice",
  "Fire",
  "Flame",
  "Spark",
  "Glow",
  "Shine",
  "Glitter",
  "Sparkle",
  "Twinkle",
  "Flicker",
  "Flash",
  "Blink",
  "Wink",
  "Blink",
  "Wink",
  "Nod",
  "Wave",
  "Shake",
  "Rock",
  "Sway",
  "Swing",
  "Bounce",
  "Jump",
  "Hop",
  "Skip",
  "Run",
  "Walk",
  "Stroll",
  "Saunter",
  "Amble",
  "Wander",
  "Roam",
  "Explore",
  "Discover",
  "Find",
  "Seek",
  "Search",
  "Look",
  "See",
  "Watch",
  "Observe",
  "Notice",
  "Spot",
  "Catch",
  "Grab",
  "Take",
  "Hold",
  "Keep",
  "Save",
  "Store",
  "Collect",
  "Gather",
  "Assemble",
  "Build",
  "Create",
  "Make",
  "Form",
  "Shape",
  "Mold",
  "Cast",
  "Pour",
  "Fill",
  "Empty",
  "Drain",
  "Flow",
  "Stream",
  "River",
  "Ocean",
  "Sea",
  "Lake",
  "Pond",
  "Pool",
  "Puddle",
  "Drop",
  "Drip",
  "Leak",
  "Spill",
  "Overflow",
  "Flood",
  "Drown",
  "Sink",
  "Float",
  "Swim",
  "Dive",
  "Plunge",
  "Jump",
  "Leap",
  "Bound",
  "Spring",
  "Bounce",
  "Rebound",
  "Echo",
  "Resound",
  "Ring",
  "Chime",
  "Bell",
  "Clock",
  "Watch",
  "Time",
  "Hour",
  "Minute",
  "Second",
  "Day",
  "Night",
  "Morning",
  "Evening",
  "Afternoon",
  "Midnight",
  "Noon",
  "Dawn",
  "Dusk",
  "Sunrise",
  "Sunset",
  "Twilight",
  "Gloaming",
  "Daybreak",
  "Nightfall",
  "Bedtime",
  "Wake",
  "Sleep",
  "Dream",
  "Nightmare",
  "Vision",
  "Sight",
  "View",
  "Scene",
  "Picture",
  "Image",
  "Photo",
  "Snapshot",
  "Portrait",
  "Landscape",
  "Still Life",
  "Abstract",
  "Modern",
  "Contemporary",
  "Traditional",
  "Classical",
  "Ancient",
  "Old",
  "New",
  "Fresh",
  "Stale",
  "Rotten",
  "Spoiled",
  "Good",
  "Bad",
  "Better",
  "Worse",
  "Best",
  "Worst",
  "Perfect",
  "Imperfect",
  "Flawed",
  "Flawless",
  "Beautiful",
  "Ugly",
  "Pretty",
  "Handsome",
  "Attractive",
  "Unattractive",
  "Gorgeous",
  "Stunning",
  "Striking",
  "Dramatic",
  "Bold",
  "Subtle",
  "Delicate",
  "Fragile",
  "Strong",
  "Weak",
  "Powerful",
  "Helpless",
  "Independent",
  "Dependent",
  "Free",
  "Bound",
  "Trapped",
  "Liberated",
  "Enslaved",
  "Happy",
  "Sad",
  "Joyful",
  "Miserable",
  "Content",
  "Discontent",
  "Satisfied",
  "Unsatisfied",
  "Fulfilled",
  "Unfulfilled",
  "Complete",
  "Incomplete",
  "Finished",
  "Unfinished",
  "Done",
  "Undone",
  "Made",
  "Unmade",
  "Built",
  "Destroyed",
  "Created",
  "Ruined",
  "Formed",
  "Deformed",
  "Shaped",
  "Misshapen",
  "Perfect",
  "Imperfect",
  "Flawed",
  "Flawless",
  "Beautiful",
  "Ugly",
  "Pretty",
  "Handsome",
  "Attractive",
  "Unattractive",
  "Gorgeous",
  "Stunning",
  "Striking",
  "Dramatic",
  "Bold",
  "Subtle",
  "Delicate",
  "Fragile",
  "Strong",
  "Weak",
  "Powerful",
  "Helpless",
  "Independent",
  "Dependent",
  "Free",
  "Bound",
  "Trapped",
  "Liberated",
  "Enslaved",
  "Happy",
  "Sad",
  "Joyful",
  "Miserable",
  "Content",
  "Discontent",
  "Satisfied",
  "Unsatisfied",
  "Fulfilled",
  "Unfulfilled",
  "Complete",
  "Incomplete",
  "Finished",
  "Unfinished",
  "Done",
  "Undone",
  "Made",
  "Unmade",
  "Built",
  "Destroyed",
  "Created",
  "Ruined",
  "Formed",
  "Deformed",
  "Shaped",
  "Misshapen"
] as const;

export type StyleTag = typeof ALLOWED_STYLE_TAGS[number]; 